### ISSUE TITLE
FAQ Install

### ISSUE THREAD

**Issue by OeziDev** [SquadMS/Squad-MS#1]
Is there a manual, how we install SquadMS?

**Comment by bumbummen99** [comment]
There is no manual currently and i am not sure if there ever will be. SquadMS is Laravel so basically checkout the [documentation](https://laravel.com/docs/8.x/installation#meet-laravel) for Laravel.
To install just follow from the following link to setup and start Sail to run composer/npm install in your container afterwards to install dependencies. You will need docker for that.

https://laravel.com/docs/8.x/sail#configuring-a-bash-alias

**Comment by bumbummen99** [comment]
I have put the necessary information in the Readme:
https://github.com/SquadMS/Squad-MS/blob/master/README.md#installation-development
