### ISSUE TITLE
please give a easier document

### ISSUE THREAD

**Issue by willyautoman** [SquadMS/Squad-MS#63]
I want use Ubuntu22.04 to deploy your system ,but when I read the document ,i can't deploy it successfully,so can you make an easier document for the user of SquadMS

**Comment by bumbummen99** [comment]
The guide in the readme was actually written on 22.04. What exactly did not work when you tried to deploy it?

**Comment by willyautoman** [comment]
if i just want to use it ,rather then develop it ,hao can I startup ?I only see the tutorial of development.Please give an tutorial for use only.

**Comment by willyautoman** [comment]
Thank you very much for sharing such a detailed tutorial，hope you can add the hard requirements to the readme.I believe the squadms can be deployed smoothly through your above description.
